# Generated by Django 5.1.3 on 2024-11-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_chassis_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_engine_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_tag_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_year_model',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
