# Generated by Django 5.1.3 on 2024-11-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_bus_bus_chassis_num_alter_bus_bus_engine_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_unit_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
