# Generated by Django 5.1.3 on 2024-11-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_contact_num',
            field=models.CharField(max_length=11),
        ),
    ]
