# Generated by Django 5.1.3 on 2024-11-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_alter_employee_emp_contact_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
