# Generated by Django 5.1.3 on 2024-11-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_material_mat_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='purchase_order',
            new_name='PurchaseOrder',
        ),
        migrations.RenameModel(
            old_name='purchase_order_status',
            new_name='PurchaseOrderStatus',
        ),
    ]
