# Generated by Django 5.1.3 on 2024-12-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0013_job_order_status_remove_material_order_sup_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
