# Generated by Django 5.1.3 on 2024-12-01 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0014_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRequest',
            fields=[
                ('job_order', models.AutoField(primary_key=True, serialize=False)),
                ('employee_number', models.CharField(max_length=50)),
                ('bus_number', models.CharField(max_length=50)),
                ('date_requested', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
            ],
        ),
    ]
