# Generated by Django 5.1.3 on 2024-12-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_delete_driverrequest_remove_job_order_jo_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('primary_k', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
