# Generated by Django 5.1.3 on 2024-12-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0017_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_name',
            new_name='username',
        ),
    ]
