# Generated by Django 5.1.3 on 2024-12-07 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0021_employee_emp_image_alter_employee_dept_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shared.employee')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Acknowledgment_Receipt',
            fields=[
                ('ar_num', models.AutoField(primary_key=True, serialize=False)),
                ('ar_date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('ar_date_received', models.DateField()),
                ('ar_note', models.TextField()),
                ('ar_date_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Req_Status',
            fields=[
                ('IR_STAT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('IR_STAT_STATUS', models.CharField(choices=[('Waiting', 'Waiting'), ('Ongoing', 'Ongoing'), ('Done', 'Done')], default='Waiting', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Request',
            fields=[
                ('item_req_num', models.AutoField(primary_key=True, serialize=False)),
                ('item_req_date_requested', models.DateField()),
                ('item_req_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Order_Status',
            fields=[
                ('jostat_id', models.AutoField(primary_key=True, serialize=False)),
                ('jostat_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material_Category',
            fields=[
                ('mat_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('mat_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Material_Requested',
            fields=[
                ('mat_req_id', models.AutoField(primary_key=True, serialize=False)),
                ('mat_req_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Material_Used',
            fields=[
                ('mat_used_id', models.AutoField(primary_key=True, serialize=False)),
                ('mat_used_name', models.CharField(max_length=200)),
                ('mat_used_qty', models.IntegerField()),
                ('mat_used_brand', models.CharField(blank=True, max_length=200, null=True)),
                ('mat_used_measurement', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order_Status',
            fields=[
                ('postat_id', models.AutoField(primary_key=True, serialize=False)),
                ('postat_status', models.CharField(choices=[('Waiting', 'Waiting'), ('Ongoing', 'Ongoing'), ('Done', 'Done')], default='Waiting', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='mat_code',
        ),
        migrations.AlterField(
            model_name='material_order',
            name='mat_odr_measurement',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='po_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.employee'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='po_datemade',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='sup_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.supplier'),
        ),
        migrations.AddField(
            model_name='item_request',
            name='bus_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.joborder'),
        ),
        migrations.AddField(
            model_name='item_request',
            name='irstat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.item_req_status'),
        ),
        migrations.AddField(
            model_name='item_request',
            name='item_req_approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.employee'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='jostat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.job_order_status'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mat_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.material_category'),
        ),
        migrations.AddField(
            model_name='material_requested',
            name='mat_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.material'),
        ),
        migrations.AddField(
            model_name='item_request',
            name='mat_req_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.material_requested'),
        ),
        migrations.AddField(
            model_name='acknowledgment_receipt',
            name='mat_req_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.material_requested'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='mat_used_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.material_used'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='postat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.purchase_order_status'),
        ),
        migrations.DeleteModel(
            name='JobOrderStatus',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderStatus',
        ),
    ]
