# Generated by Django 5.1.3 on 2024-12-07 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0022_accounts_acknowledgment_receipt_item_req_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='j_o_work_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='jostat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.job_order_status'),
        ),
    ]
