# Generated by Django 5.1.4 on 2025-01-01 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0026_remove_item_request_irstat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_request',
            name='item_req_date_requested',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
