# Generated by Django 5.1.4 on 2025-01-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0028_alter_item_request_bus_unit_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_requested',
            name='mat_req_qty',
            field=models.PositiveIntegerField(),
        ),
    ]
