# Generated by Django 5.1.4 on 2025-01-02 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0031_alter_purchase_order_mat_odr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_order',
            name='mat_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.material_order_category'),
        ),
    ]
