# Generated by Django 5.1.4 on 2025-01-04 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0033_material_mat_max_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acknowledgment_receipt',
            name='mat_req_id',
        ),
        migrations.CreateModel(
            name='Material_Approved',
            fields=[
                ('item_approved_id', models.AutoField(primary_key=True, serialize=False)),
                ('ir_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.item_request')),
                ('mat_req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.material_requested')),
            ],
        ),
        migrations.AddField(
            model_name='acknowledgment_receipt',
            name='item_approved_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shared.material_approved'),
            preserve_default=False,
        ),
    ]
