# Generated by Django 5.1.4 on 2025-01-05 13:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0034_remove_acknowledgment_receipt_mat_req_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material_approved',
            old_name='item_approved_id',
            new_name='mat_approved_id',
        ),
        migrations.AddField(
            model_name='material_approved',
            name='date_approved',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material_approved',
            name='mat_approved_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shared.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material_approved',
            name='mat_approved_qty',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material_approved',
            name='mat_req_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_materials', to='shared.material_requested'),
        ),
    ]
