# Generated by Django 5.1.4 on 2025-01-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0035_rename_item_approved_id_material_approved_mat_approved_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgment_receipt',
            name='ar_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
