# Generated by Django 5.1.4 on 2025-01-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0037_alter_acknowledgment_receipt_ar_date_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_requested',
            name='mat_req_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
    ]
