# Generated by Django 5.1.4 on 2025-01-06 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0038_material_requested_mat_req_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_approved',
            name='ar_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.acknowledgment_receipt'),
        ),
    ]
