# Generated by Django 5.1.4 on 2025-01-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0039_material_approved_ar_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_approved',
            name='mat_approved_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.material'),
        ),
    ]
