# Generated by Django 5.1.4 on 2025-01-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0040_alter_material_approved_mat_approved_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_approved',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
