# Generated by Django 5.1.4 on 2025-01-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0041_material_approved_is_acknowledged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='j_o_work_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
