# Generated by Django 5.1.4 on 2025-01-11 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0041_material_approved_is_acknowledged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_order',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.purchase_order'),
        ),
    ]
