# Generated by Django 5.1.4 on 2025-01-11 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0042_alter_material_order_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_order',
            name='mat_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shared.material_order_category'),
            preserve_default=False,
        ),
    ]
