# Generated by Django 5.1.4 on 2025-01-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0042_item_request_job_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_unit_num',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
