# Generated by Django 5.1.4 on 2025-01-11 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0043_alter_material_order_mat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_order',
            name='mat_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.material_category'),
        ),
    ]
