# Generated by Django 5.1.4 on 2025-01-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0043_alter_bus_bus_unit_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_unit_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
