# Generated by Django 5.1.4 on 2025-01-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0044_alter_material_order_mat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_order',
            name='mat_odr_brand',
            field=models.CharField(blank=True, default='Generic', max_length=100, null=True),
        ),
    ]
