# Generated by Django 5.1.4 on 2025-01-11 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0047_alter_bus_bus_unit_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_request',
            name='item_req_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.employee'),
        ),
    ]
