# Generated by Django 5.1.4 on 2025-01-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0045_alter_bus_bus_unit_num'),
        ('shared', '0048_alter_item_request_item_req_approved_by'),
    ]

    operations = [
    ]
