# Generated by Django 5.1.4 on 2025-01-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0042_alter_joborder_j_o_work_description'),
        ('shared', '0049_merge_20250112_1448'),
    ]

    operations = [
    ]
