# Generated by Django 5.1.4 on 2025-01-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0050_merge_20250112_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_requested',
            name='item_req_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to='shared.item_request'),
        ),
    ]
