# Generated by Django 5.1.4 on 2025-01-12 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0051_alter_material_requested_item_req_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_request',
            name='mat_odr_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.material_order'),
        ),
        migrations.AddField(
            model_name='material_order',
            name='item_req_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.item_request'),
        ),
        migrations.AddField(
            model_name='material_order',
            name='mat_odr_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
    ]
