# Generated by Django 5.1.4 on 2025-01-13 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0052_item_request_mat_odr_id_material_order_item_req_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_request',
            name='mat_odr_id',
        ),
        migrations.RemoveField(
            model_name='material_order',
            name='item_req_num',
        ),
        migrations.RemoveField(
            model_name='material_order',
            name='mat_odr_status',
        ),
        migrations.AlterField(
            model_name='joborder',
            name='j_o_work_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material_requested',
            name='item_req_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.item_request'),
        ),
    ]
