# Generated by Django 5.1.3 on 2024-11-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_unit_num', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('bus_license_plate_number', models.CharField(max_length=10)),
                ('bus_chassis_num', models.IntegerField(max_length=10)),
                ('bus_engine_num', models.IntegerField(max_length=10)),
                ('bus_year_model', models.IntegerField(blank=True, max_length=4, null=True)),
                ('bus_tag_num', models.IntegerField(max_length=10)),
            ],
        ),
    ]
