# Generated by Django 5.1.3 on 2024-11-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_alter_bus_bus_unit_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mat_code', models.AutoField(primary_key=True, serialize=False)),
                ('mat_name', models.CharField(max_length=200)),
                ('mat_type', models.CharField(blank=True, max_length=200, null=True)),
                ('mat_quantity', models.IntegerField()),
                ('mat_brand', models.CharField(default='generic', max_length=200)),
                ('mat_measurement', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
