# Generated by Django 5.1.3 on 2024-11-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_name', models.CharField(max_length=300)),
                ('sup_descript', models.TextField()),
            ],
        ),
    ]
