# Generated by Django 5.1.3 on 2024-11-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=200)),
                ('dept_descript', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_descript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
