# Generated by Django 5.1.3 on 2024-11-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_department_alter_supplier_sup_descript'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_fname', models.CharField(max_length=100)),
                ('emp_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('emp_lname', models.CharField(max_length=100)),
                ('emp_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_date_of_birth', models.DateField()),
                ('emp_sex', models.CharField(max_length=6)),
                ('emp_address', models.CharField(max_length=200)),
                ('emp_role', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_contact_num', models.BigIntegerField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.department')),
            ],
        ),
    ]
