# Generated by Django 5.1.3 on 2024-11-29 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_delete_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_order_status',
            fields=[
                ('postat_id', models.AutoField(primary_key=True, serialize=False)),
                ('postat_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_name', models.CharField(max_length=300)),
                ('sup_descript', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='purchase_order',
            fields=[
                ('po_num', models.AutoField(primary_key=True, serialize=False)),
                ('po_descript', models.TextField()),
                ('po_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.employee')),
                ('po_stat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.purchase_order_status')),
                ('sup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.supplier')),
            ],
        ),
    ]
