# Generated by Django 5.1.3 on 2024-12-03 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0015_driverrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverRequest',
        ),
        migrations.RemoveField(
            model_name='job_order',
            name='JO_approved_by',
        ),
        migrations.RemoveField(
            model_name='job_order',
            name='JO_checked_by',
        ),
        migrations.RemoveField(
            model_name='job_order',
            name='bus_unit_num',
        ),
        migrations.RemoveField(
            model_name='job_order',
            name='jostat_id',
        ),
        migrations.RemoveField(
            model_name='job_order',
            name='mat_code',
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.RemoveField(
            model_name='material_order',
            name='po_num',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_approved_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_stat_id',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.AlterField(
            model_name='employee',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='shared.department'),
        ),
        migrations.DeleteModel(
            name='Job_Order_Status',
        ),
        migrations.DeleteModel(
            name='Job_Order',
        ),
        migrations.DeleteModel(
            name='material_order',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
