# Generated by Django 5.1.3 on 2024-12-03 10:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0018_rename_account_name_account_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrderStatus',
            fields=[
                ('jostat_id', models.AutoField(primary_key=True, serialize=False)),
                ('jostat_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('j_o_number', models.AutoField(primary_key=True, serialize=False)),
                ('j_o_date_requested', models.DateField(default=django.utils.timezone.now)),
                ('j_o_work_description', models.TextField()),
                ('j_o_date_completed', models.DateField(blank=True, null=True)),
                ('j_o_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by', to='shared.employee')),
                ('j_o_bus_unit_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.bus')),
                ('j_o_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_by', to='shared.employee')),
                ('mat_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.material')),
                ('jostat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.joborderstatus')),
            ],
        ),
    ]
