# Generated by Django 5.1.3 on 2024-12-03 10:50

import django.db.models.deletion
import shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0019_joborderstatus_joborder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_Order_Category',
            fields=[
                ('mat_odr_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('mat_odr_cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_name', models.CharField(max_length=300)),
                ('sup_descript', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('po_num', models.AutoField(primary_key=True, serialize=False)),
                ('po_description', models.TextField(blank=True, null=True)),
                ('po_datemade', models.DateField()),
                ('mat_odr_id', models.ForeignKey(default=shared.models.get_default_material_order_category, on_delete=django.db.models.deletion.CASCADE, to='shared.material_order_category')),
                ('po_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.employee')),
                ('postat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.purchaseorderstatus')),
                ('sup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Material_Order',
            fields=[
                ('mat_odr_id', models.AutoField(primary_key=True, serialize=False)),
                ('mat_odr_name', models.CharField(max_length=100)),
                ('mat_odr_qty', models.IntegerField()),
                ('mat_odr_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('mat_odr_measurement', models.IntegerField(blank=True, null=True)),
                ('mat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.material_order_category')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.purchase_order')),
            ],
        ),
    ]
