# Generated by Django 5.1.4 on 2024-12-27 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0024_rename_bus_num_item_request_bus_unit_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_requested',
            name='item_req_num',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shared.item_request'),
            preserve_default=False,
        ),
    ]
