# Generated by Django 5.1.4 on 2025-01-01 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0027_alter_item_request_item_req_date_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_request',
            name='bus_unit_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.bus'),
        ),
    ]
