# Generated by Django 5.1.4 on 2025-01-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0029_alter_material_requested_mat_req_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='mat_type',
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
