# Generated by Django 5.1.4 on 2025-01-02 09:43

import django.db.models.deletion
import shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0030_remove_material_mat_type_material_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='mat_odr_id',
            field=models.ForeignKey(blank=True, default=shared.models.get_default_material_order_category, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.material_order_category'),
        ),
    ]
